using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using UnityEditor;
using System.IO;
using UnityEngine.ResourceManagement.AsyncOperations;
using UnityEngine.AddressableAssets;

[CreateAssetMenu(fileName = "CountryResources", menuName = "ScriptableObjects/CountryResources")]
public class CountryResources : ScriptableObject
{
    public List<CountryData> CountryDatas;

    public CountryData GetDataByCode(string countryCode)
    {
        string code = countryCode.ToUpper();
        CountryData data = CountryDatas.Find(item => item.Code == code);
        if (data == null)
        {
            data = CountryDatas.Find(item => item.Code == "US");
        }

        return data;
    }

#if UNITY_EDITOR
    [ContextMenu("Execute")]
    public void Execute()
    {
        CountryDatas = new List<CountryData>();

        AsyncOperationHandle<Sprite[]> spriteHandle = Addressables.LoadAssetAsync<Sprite[]>("CountryIcon");
        spriteHandle.Completed += handleToCheck =>
        {
            List<Sprite> spriteList = new List<Sprite>();
            spriteList.AddRange(handleToCheck.Result);

            for (int i = 0; i < countriesCode.Length; i++)
            {
                CountryData countryData = new CountryData();
                countryData.Code = countriesCode[i];
                countryData.Name = countriesName[i];
                countryData.Sprite = spriteList.Find(item => item.name == countryData.Code);

                CountryDatas.Add(countryData);
            }
        };
    }

    private string[] countriesName = {
        "India",
        "United States of America",
        "Russian Federation",
        "Indonesia",
        "Pakistan",
        "Germany",
        "Egypt",
        "Philippines",
        "Iraq",
        "France",
        "Japan",
        "Korea (the Republic of Korea)",
        "Ukraine",
        "Iran",
        "United Kingdom of Great Britain and Northern Ireland",
        "Malaysia",
        "Brazil",
        "Canada",
        "Uzbekistan",
        "Taiwan",
        "Turkey",
        "Bangladesh",
        "Viet Nam",
        "Cambodia",
        "Kazakhstan",
        "Poland",
        "Algeria",
        "South Africa",
        "Myanmar",
        "Thailand",
        "Australia",
        "Italy",
        "Sri Lanka",
        "Morocco",
        "Mexico",
        "Spain",
        "New Zealand",
        "Switzerland",
        "Kyrgyzstan",
        "Saudi Arabia",
        "Argentina",
        "Belarus",
        "Greece",
        "Czechia",
        "Hungary",
        "Netherlands",
        "Hong Kong",
        "Romania",
        "Colombia",
        "Nepal",
        "Portugal",
        "Norway",
        "Peru",
        "Azerbaijan",
        "United Arab Emirates",
        "Austria",
        "Bulgaria",
        "Jordan",
        "Tunisia",
        "Turkmenistan",
        "Belgium",
        "Lebanon",
        "Israel",
        "Venezuela",
        "Nigeria",
        "Serbia",
        "Tajikistan",
        "Ecuador",
        "Chile",
        "Afghanistan",
        "Slovakia",
        "Syrian Arab Republic",
        "Guatemala",
        "Kenya",
        "Yemen",
        "Dominican Republic",
        "Lao People's Democratic Republic",
        "Croatia",
        "Sweden",
        "Georgia",
        "Libya",
        "Oman",
        "Mongolia",
        "Ghana",
        "Singapore",
        "Moldova",
        "Palestine",
        "Finland",
        "Bolivia",
        "Ireland",
        "Armenia",
        "Lithuania",
        "Denmark",
        "Honduras",
        "El Salvador",
        "Albania",
        "Qatar",
        "Slovenia",
        "China",
        "Sudan",
        "Latvia",
        "Costa Rica",
        "Uruguay",
        "Tanzania",
        "Kuwait",
        "Mauritius",
        "Senegal",
        "Uganda",
        "Panama",
        "Jamaica",
        "Bosnia and Herzegovina",
        "Fiji",
        "Puerto Rico",
        "Paraguay",
        "Trinidad and Tobago",
        "Cyprus",
        "Ethiopia",
        "Nicaragua",
        "Côte d'Ivoire",
        "Cameroon",
        "Haiti",
        "Estonia",
        "Réunion",
        "Congo (the Democratic Republic of the Congo)",
        "Somalia",
        "Madagascar",
        "Guyana",
        "Papua New Guinea",
        "Mali",
        "Zimbabwe",
        "Macedonia",
        "Bhutan",
        "Namibia",
        "Bahrain",
        "Suriname",
        "Kosovo",
        "Maldives",
        "Burkina Faso",
        "Malta",
        "Brunei Darussalam",
        "New Caledonia",
        "Gabon",
        "Benin",
        "Guadeloupe",
        "Cuba",
        "Montenegro",
        "Timor-Leste",
        "Zambia",
        "Luxembourg",
        "Botswana",
        "Mozambique",
        "Togo",
        "Guinea",
        "Angola",
        "French Polynesia",
        "Belize",
        "Iceland",
        "Mauritania",
        "Niger",
        "Tonga",
        "Rwanda",
        "Macao",
        "Western Sahara",
        "Bahamas",
        "Barbados",
        "Djibouti",
        "Kiribati",
        "Cabo Verde",
        "Guam",
        "Saint Lucia",
        "Martinique",
        "Samoa",
        "Sierra Leone",
        "Eswatini",
        "Malawi",
        "Solomon Islands",
        "Cayman Islands",
        "Micronesia",
        "Curaçao",
        "Jersey",
        "French Guiana",
        "Seychelles",
        "Mayotte",
        "Antigua and Barbuda",
        "Greenland",
        "Burundi",
        "Liberia",
        "Gambia",
        "Saint Vincent and the Grenadines",
        "Chad",
        "Congo",
        "Virgin Islands (U.S.)",
        "Central African Republic",
        "American Samoa",
        "Palau",
        "Andorra",
        "Equatorial Guinea",
        "Marshall Islands",
        "Comoros",
        "Grenada",
        "Gibraltar",
        "Lesotho",
        "Vanuatu",
        "Montserrat",
        "South Sudan",
        "Dominica",
        "Aruba",
        "Liechtenstein",
        "Sint Maarten (Dutch part)",
        "Bonaire, Sint Eustatius, and Saba",
        "Bermuda",
        "Saint Martin (French part)",
        "San Marino",
        "Eritrea",
        "Sao Tome and Principe",
        "Cook Islands",
        "Saint Kitts and Nevis",
        "Guinea-Bissau",
        "Virgin Islands (British)",
        "Tuvalu",
        "Turks and Caicos Islands",
        "Nauru",
        "Faroe Islands",
        "Guernsey",
        "Northern Mariana Islands",
        "Niue",
        "Anguilla",
        "Saint Barthélemy",
        "Monaco",
        "Åland Islands",
    };
    private string[] countriesCode = {
        "IN",
        "US",
        "RU",
        "ID",
        "PK",
        "DE",
        "EG",
        "PH",
        "IQ",
        "FR",
        "JP",
        "KR",
        "UA",
        "IR",
        "GB",
        "MY",
        "BR",
        "CA",
        "UZ",
        "TW",
        "TR",
        "BD",
        "VN",
        "KH",
        "KZ",
        "PL",
        "DZ",
        "ZA",
        "MM",
        "TH",
        "AU",
        "IT",
        "LK",
        "MA",
        "MX",
        "ES",
        "NZ",
        "CH",
        "KG",
        "SA",
        "AR",
        "BY",
        "GR",
        "CZ",
        "HU",
        "NL",
        "HK",
        "RO",
        "CO",
        "NP",
        "PT",
        "NO",
        "PE",
        "AZ",
        "AE",
        "AT",
        "BG",
        "JO",
        "TN",
        "TM",
        "BE",
        "LB",
        "IL",
        "VE",
        "NG",
        "RS",
        "TJ",
        "EC",
        "CL",
        "AF",
        "SK",
        "SY",
        "GT",
        "KE",
        "YE",
        "DO",
        "LA",
        "HR",
        "SE",
        "GE",
        "LY",
        "OM",
        "MN",
        "GH",
        "SG",
        "MD",
        "PS",
        "FI",
        "BO",
        "IE",
        "AM",
        "LT",
        "DK",
        "HN",
        "SV",
        "AL",
        "QA",
        "SI",
        "CN",
        "SD",
        "LV",
        "CR",
        "UY",
        "TZ",
        "KW",
        "MU",
        "SN",
        "UG",
        "PA",
        "JM",
        "BA",
        "FJ",
        "PR",
        "PY",
        "TT",
        "CY",
        "ET",
        "NI",
        "CI",
        "CM",
        "HT",
        "EE",
        "RE",
        "CD",
        "SO",
        "MG",
        "GY",
        "PG",
        "ML",
        "ZW",
        "MK",
        "BT",
        "NA",
        "BH",
        "SR",
        "XK",
        "MV",
        "BF",
        "MT",
        "BN",
        "NC",
        "GA",
        "BJ",
        "GP",
        "CU",
        "ME",
        "TL",
        "ZM",
        "LU",
        "BW",
        "MZ",
        "TG",
        "GN",
        "AO",
        "PF",
        "BZ",
        "IS",
        "MR",
        "NE",
        "TO",
        "RW",
        "MO",
        "EH",
        "BS",
        "BB",
        "DJ",
        "KI",
        "CV",
        "GU",
        "LC",
        "MQ",
        "WS",
        "SL",
        "SZ",
        "MW",
        "SB",
        "KY",
        "FM",
        "CW",
        "JE",
        "GF",
        "SC",
        "YT",
        "AG",
        "GL",
        "BI",
        "LR",
        "GM",
        "VC",
        "TD",
        "CG",
        "VI",
        "CF",
        "AS",
        "PW",
        "AD",
        "GQ",
        "MH",
        "KM",
        "GD",
        "GI",
        "LS",
        "VU",
        "MS",
        "SS",
        "DM",
        "AW",
        "LI",
        "SX",
        "BQ",
        "BM",
        "MF",
        "SM",
        "ER",
        "ST",
        "CK",
        "KN",
        "GW",
        "VG",
        "TV",
        "TC",
        "NR",
        "FO",
        "GG",
        "MP",
        "NU",
        "AI",
        "BL",
        "MC",
        "AX"
    };
#endif
}

[Serializable]
public class CountryData
{
    public string Name;
    public string Code;
    public Sprite Sprite;
}
